name: practiceplugins
main: me.jordyn.Plugin
version: '${project.version}'
api-version: '1.20'
commands:
  fly:
    usage: /<command>
    permission: practiceplugins.fly
    permission-message: You do not have <permission>!
permissions:
  practiceplugins.fly:
    description: Allows /fly command